[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/noctalia.toml"]
ipc_socket = true

[env]
TERM = "alacritty-direct"

[selection]
save_to_clipboard = true

[cursor]
# Always blinking cursor.
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Always" }

[[keyboard.bindings]]
  action = "ToggleFullscreen"
  key = "F11"
  mods = "None"
