[config]
version_check = false

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "random"]
set = true

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/matugen.toml'

[templates.emacs]
input_path = '~/.config/matugen/templates/emacs.el'
output_path = '~/.emacs.d/var/matugen/matugen.el'
post_hook = "emacsclient --eval '(progn (load-file \"~/.emacs.d/var/matugen/matugen.el\") (load-theme (car custom-enabled-themes) t))'"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/matugen.conf'
post_hook = 'hyprctl reload'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qt.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qt.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

# Currently, Starship has no concept of sourcing/including a separate
# configuration file, so it's template will not be used.

[templates.television]
input_path = '~/.config/matugen/templates/television.toml'
output_path = '~/.config/television/themes/matugen.toml'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/matugen.css'
post_hook = 'killall -SIGUSR2 waybar'
