[general]
always_show_help_enabled = false
confirm_quit.enabled = true
collapsed_sections = []
refresh_on_file_change.enabled = true
stash_list_limit = 10
recent_commits_limit = 10
mouse_support = false
mouse_scroll_lines = 3
confirm_discard = "line"

# Emacsy keybinds.
[bindings]
root.copy_hash = ["ctrl+w"]
root.discard = ["k"]
root.quit = ["q", "esc"]
root.refresh = ["g"]
root.show = ["enter"]
root.show_refs = ["y"]
root.stage = ["s"]
root.unstage = ["u"]
root.toggle_section = ["tab"]

root.move_up = ["p", "up"]
root.move_down = ["n", "down"]
root.move_up_line = ["ctrl+p", "ctrl+up"]
root.move_down_line = ["ctrl+n", "ctrl+down"]
root.move_prev_section = ["alt+p", "alt+up"]
root.move_next_section = ["alt+n", "alt+down"]
root.move_parent_section = ["^"]
root.half_page_up = ["alt+v"]
root.half_page_down = ["ctrl+v"]

root.help_menu = ["h", "?"]
root.branch_menu = ["b"]
root.commit_menu = ["c"]
root.fetch_menu = ["f"]
root.log_menu = ["l"]

help_menu.quit = ["q", "h", "?", "esc", "ctrl+g"]

branch_menu.checkout = ["b"]
branch_menu.checkout_new_branch = ["c"]
branch_menu.quit = ["q", "esc", "ctrl+g"]
root.pull_menu = ["F"]
root.push_menu = ["P"]
root.rebase_menu = ["r"]
root.reset_menu = ["X"]
root.revert_menu = ["V"]
root.stash_menu = ["z"]

commit_menu.--all = ["-a"]
commit_menu.--allow-empty = ["-e"]
commit_menu.--verbose = ["-v"]
commit_menu.--no-verify = ["-n"]
commit_menu.--reset-author = ["-R"]
commit_menu.--signoff = ["-s"]
commit_menu.commit = ["c"]
commit_menu.commit_amend = ["a"]
commit_menu.commit_fixup = ["f"]
commit_menu.commit_instant_fixup = ["F"]
commit_menu.quit = ["q", "esc", "ctrl+g"]

fetch_menu.--prune = ["-p"]
fetch_menu.--tags = ["-t"]
fetch_menu.fetch_all = ["a"]
fetch_menu.quit = ["q", "esc", "ctrl+g"]
fetch_menu.fetch_elsewhere = ["e"]

log_menu.log_current = ["l"]
log_menu.log_other = ["o"]
log_menu.quit = ["q", "esc", "ctrl+g"]
log_menu.-n = ["-n"]
log_menu.--grep = ["-F"]

pull_menu.--rebase = ["-r"]
pull_menu.pull_from_push_remote = ["p"]
pull_menu.pull_from_upstream = ["u"]
pull_menu.pull_from_elsewhere = ["e"]
pull_menu.quit = ["q", "esc", "ctrl+g"]

push_menu.--force-with-lease = ["-f"]
push_menu.--force = ["-F"]
push_menu.--no-verify = ["-h"]
push_menu.--dry-run = ["-n"]
push_menu.push_to_push_remote = ["p"]
push_menu.push_to_upstream = ["u"]
push_menu.push_to_elsewhere = ["e"]
push_menu.quit = ["q", "esc", "ctrl+g"]

rebase_menu.--keep-empty = ["-k"]
rebase_menu.--preserve-merges = ["-p"]
rebase_menu.--committer-date-is-author-date = ["-d"]
rebase_menu.--autosquash = ["-a"]
rebase_menu.--autostash = ["-A"]
rebase_menu.--interactive = ["-i"]
rebase_menu.--no-verify = ["-h"]
rebase_menu.rebase_interactive = ["i"]
rebase_menu.rebase_abort = ["a"]
rebase_menu.rebase_continue = ["c"]
rebase_menu.rebase_elsewhere = ["e"]
rebase_menu.rebase_autosquash = ["f"]
rebase_menu.quit = ["q", "esc", "ctrl+g"]

reset_menu.reset_soft = ["s"]
reset_menu.reset_mixed = ["m"]
reset_menu.reset_hard = ["h"]
reset_menu.quit = ["q", "esc", "ctrl+g"]

revert_menu.--edit = ["-e"]
revert_menu.--no-edit = ["-E"]
revert_menu.--signoff = ["-s"]
revert_menu.revert_abort = ["a"]
revert_menu.revert_continue = ["c"]
revert_menu.revert_commit = ["V"]
revert_menu.quit = ["q", "esc", "ctrl+g"]

stash_menu.--all = ["-a"]
stash_menu.--include-untracked = ["-u"]
stash_menu.stash = ["z"]
stash_menu.stash_index = ["i"]
stash_menu.stash_worktree = ["w"]
stash_menu.stash_keep_index = ["x"]
stash_menu.stash_pop = ["p"]
stash_menu.stash_apply = ["a"]
stash_menu.stash_drop = ["k"]
stash_menu.quit = ["q", "esc", "ctrl+g"]
